name: dbt_composer_on_gcp
profile: dbt_composer_on_gcp
version: '1.0.0'
config-version: 2

model-paths: ["models"]

target-path: "target"
clean-targets:
    - "target"
    - "dbt_modules"

models:
    dbt_composer_on_gcp:
        raw:
            schema: de_raw
        intermediate:
            schema: de_intermediate
        datamart:
            schema: de_datamart
    +persist_docs:
        relation: true 
        columns: true