dbt_composer_on_gcp:
  outputs:
    dev:
      dataset: demo_dataset_dts
      job_execution_timeout_seconds: 500
      job_retries: 1
      location: US
      method: oauth
      priority: interactive
      project: td2bq-demo
      threads: 2
      type: bigquery
  target: dev
